@startuml
[*] -> 了解自我
了解自我 -> 了解所有选项
了解所有选项 -> 知道我将如何决策_CASVE
知道我将如何决策_CASVE -> 思考我的决策制定过程
思考我的决策制定过程 -> [*]

state 知道我将如何决策_CASVE {
  沟通_Communication --> 分析_Analysis
  分析_Analysis --> 综合_Synthesis
  综合_Synthesis --> 评估_Valuing
  评估_Valuing --> 执行_Execution
  执行_Execution --> 沟通_Communication
}
沟通_Communication: 定位问题
分析_Analysis: 思考可选项
综合_Synthesis: 生成可行项
评估_Valuing: 优先级排序
执行_Execution: 缩小差距

了解自我: 我是谁？
了解自我: 职业生涯发展与规划的源头。
了解所有选项: 我在哪？
了解所有选项: 我可以做哪些。
思考我的决策制定过程: 自我对话
思考我的决策制定过程: 自我觉察
思考我的决策制定过程: 自我控制和监督
@enduml