@startuml
[*] -> HTML4
HTML4 -> XHTML
XHTML -> HTML5
HTML5 -> Ajax
Ajax -down-> SPA
SPA -left-> Angular
Angular -left-> React
React -left-> Vue
Vue -left-> [*]

HTML4: FrontPage
HTML4: Dreamweaver
HTML4: Flash
HTML4: 蓝色理想
HTML4: 闪客联盟
XHTML: Eric Meyer
XHTML: 《CSS禅意花园》
XHTML: 《Don't Make Me Think》
HTML5: CSS3
Ajax: Web 2.0
Ajax: jQuery
Ajax: Prototype and Scriptaculous
Ajax: mootools and YUI
Ajax: JavaScript: The good parts
SPA: Web Components
SPA: backbone.js
SPA: Angular
SPA: Node.js and Webpack
Angular: Google Gmail
React: facebook
Vue: Evan You
Vue: Vite
@enduml