@startuml
state 笔记准备 {
  state 打开软件 {
  }
  state 抓取内容 {
  }
}

state 笔记记录 {
  state 写作界面 {
  }
  state 写作界面含抓取内容 {
  }
}

[*] --> 笔记准备
打开软件 --> 写作界面
抓取内容 --> 写作界面含抓取内容
写作界面 --> 笔记预览
写作界面含抓取内容 --> 笔记预览
笔记预览 --> 笔记发布
笔记发布 --> [*]

打开软件: 简单界面，带元数据
写作界面含抓取内容: 内嵌对象
写作界面含抓取内容: 可选对象本地保存
抓取内容: 第二入口
写作界面: 现有笔记回顾
写作界面: 确定主题提问
写作界面: 围绕主题的提示
笔记预览: 本地预览
笔记预览: 远程预览
笔记发布: 发布位置
笔记发布: 是否自动发布
笔记发布: 自定义条件发布
@enduml