@startuml
[*] -> 打开软件
打开软件 -> 记笔记
[*] -> 抓取笔记
记笔记 -> 写作界面
抓取笔记 -> 写作界面
写作界面 -> 预览界面
预览界面 -> 发布
发布 -> [*]

打开软件: 简单界面，带元数据
记笔记: 默认打开，可定义入口
抓取笔记: 右键入口
写作界面: 现有笔记回顾
写作界面: 确定主题提问
写作界面: 围绕主题的提示
预览界面：本地预览
预览界面：远程预览
发布：发布位置
发布：是否自动发布
发布：发布
@enduml